# ----------------------------------------
# Non-Spring-Handled Properties
# ----------------------------------------
base-web:
  http:
    task-executor:
      core-pool-size: 50
      max-pool-size: 200
      queue-capacity: 500

ems-app:
  user-verification:
    email-subject: verification code
    code-length: 6
    code-lifespan-in-minute: 10
      
# ----------------------------------------
# Spring-Handled Properties
#
# Check the following link to see detailed explanation
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ----------------------------------------

# APPLICATION SETTINGS (SpringApplication)
spring:
  # Spring Profiles
  profiles:
    active: @ems-app.profiles.active@
    
  # SPRING CACHE (CacheProperties)
  cache:
    type: infinispan
    cache-names: verificationCode

  # SPRING MVC (WebMvcProperties)
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 300000
      
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # SPRING RESOURCES HANDLING (ResourceProperties)
  resources:
    add-mappings: false
    
  # SPRING SESSION (SessionProperties)
  session:
    store-type: mongo
    
  # MONGODB (MongoProperties)
  data:
    mongodb: 
      host: @ems-app.mongodb.host@
      port: @ems-app.mongodb.port@
      database: @ems-app.mongodb.database@
      username: @ems-app.mongodb.username@
      password: @ems-app.mongodb.password@
      authentication-database: @ems-app.mongodb.authentication-database@
      
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  context-path: /rtalpha
  tomcat:
    basedir: @ems-app.tomcat.basedir@
    accesslog:
      directory: log
      enabled: true

# SECURITY (SecurityProperties)
security:
  enable-csrf: false
  sessions: if_required
  basic:
    enabled: false